[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
fs_permissions = [{ access = "read-write", path = "./" }]
evm_version = "shanghai"

[etherscan]
mainnet = { key = "${ETH_API_KEY}", chain = 1, url = "https://api.etherscan.io/api" }
bsc = { key = "${BSC_API_KEY}", chain = 56, url = "https://api.bscscan.com/api" }
base = { key = "${BASE_API_KEY}", chain = 8453, url = "https://api.basescan.org/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
